package reb

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.

	BlockchainApi
	LocalBillApi
	ThirdPartyBillApi
	ErrorBillApi
	ReconciledBillApi
	StorageContractApi
	// Code generated by server End; DO NOT EDIT.
}
