package reb

type RouterGroup struct {
    // Code generated by server Begin; DO NOT EDIT.

	BlockchainRouter
	LocalBillRouter
	ThirdPartyBillRouter
	ErrorBillRouter
	StorageContractRouter
	ReconciledBillRouter
	// Code generated by server End; DO NOT EDIT.
}
