package reb


type ServiceGroup struct {
    // Code generated by server Begin; DO NOT EDIT.

	BlockchainService
	LocalBillService
	ThirdPartyBillService
	ErrorBillService
	StorageContractService
	ReconciledBillService
	// Code generated by server End; DO NOT EDIT.
}

